### ISSUE TITLE
COCO Panoptic data does not have 'color' attribute

### ISSUE THREAD

**Issue by Jerryzcn** [cocodataset/panopticapi#2]
Hi,
It seems that that COCO Panoptic annotation does not have 'color' attribute
http://images.cocodataset.org/annotations/panoptic_annotations_trainval2017.zip

eg.
...{"supercategory": "building", "isthing": 0, "id": 197, "name": "building-other-merged"}, {"supercategory": "solid", "isthing": 0, "id": 198, "name": "rock-merged"}, {"supercategory": "wall", "isthing": 0, "id": 199, "name": "wall-other-merged"}, {"supercategory": "textile", "isthing": 0, "id": 200, "name": "rug-merged"}]}

When I use format_converter.py I get "KeyError: 'color'"

Thanks!

**Comment by alexander-kirillov** [comment]
Thanks you for spotting the bug. The code is fixed now. We'll also update annotations later today to add colors there as well.

**Comment by cao-nv** [comment]
Have you fixed this issue? 
I got this problem today. Both panopticapi and annotations files are the latest releases

**Comment by alexander-kirillov** [comment]
There is a delay with the update due to a migration of the COCO storage. I'm sorry! Nevertheless, current data is correct. New files just have the color field and new segment ID encoding, so there is no need in waiting for them now.

You can use _panoptic_coco_categories.json_ file that has the right color for each category. Also, _format_converter.py_ has been fixed and does not require the color field anymore.

**Comment by cao-nv** [comment]
Sorry if I was wrong, but I found `format_converter.py` still used  keywords `color` here. 
https://github.com/cocodataset/panopticapi/blob/e30ca011a08665973cff46a04a618a2425857251/format_converter.py#L26
This is my command to convert the format, the `categories.json` was extracted from the annotation json file of the training data. 
```
(.global_env) cao@slspGPU1:~/workspace/data/COCO$ python panopticapi/format_converter.py --source_folder='../../COCO2018/panoptic/val' --images_json_file='annotations/panoptic_val2017.json' --categories_json_file='./annotations/categories.json' --segmentations_folder='val_seg' --predictions_json_file='val.json'
```
Output of the command! Thanks
```

Reading image set information from annotations/panoptic_val2017.json
CONVERTING...
2 channels PNG panoptic format:
        Source folder: ../../COCO2018/panoptic/val
TO
COCO format:
        Segmentation folder: val_seg
        JSON file: val.json
Number of cores: 8, images per core: 625
Core: 0, 0 from 625 images converted
Core: 1, 0 from 625 images converted
Core: 2, 0 from 625 images converted
Core: 3, 0 from 625 images converted
Core: 4, 0 from 625 images converted
Core: 5, 0 from 625 images converted
Core: 6, 0 from 625 images converted
Caught exception in worker thread:
Traceback (most recent call last):
  File "/mnt/hdd1/cao/workspace/data/COCO/panopticapi/utils.py", line 12, in wrapper
    return f(*args, **kwargs)
  File "panopticapi/format_converter.py", line 69, in convert_single_core
    color_gererator = ColorGenerator(categories)
  File "panopticapi/format_converter.py", line 26, in __init__
    self.taken_colors.add(tuple(category['color']))
KeyError: u'color'
Traceback (most recent call last):
  File "panopticapi/format_converter.py", line 156, in <module>
    args.void)
  File "panopticapi/format_converter.py", line 125, in converter
    annotations.extend(p.get())
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: u'color'
Core: 7, 0 from 625 images converted
Caught exception in worker thread:
Traceback (most recent call last):
  File "/mnt/hdd1/cao/workspace/data/COCO/panopticapi/utils.py", line 12, in wrapper
    return f(*args, **kwargs)
  File "panopticapi/format_converter.py", line 69, in convert_single_core
    color_gererator = ColorGenerator(categories)
  File "panopticapi/format_converter.py", line 26, in __init__
    self.taken_colors.add(tuple(category['color']))
KeyError: u'color'
Caught exception in worker thread:
Traceback (most recent call last):
  File "/mnt/hdd1/cao/workspace/data/COCO/panopticapi/utils.py", line 12, in wrapper
    return f(*args, **kwargs)
  File "panopticapi/format_converter.py", line 69, in convert_single_core
    color_gererator = ColorGenerator(categories)
  File "panopticapi/format_converter.py", line 26, in __init__
    self.taken_colors.add(tuple(category['color']))
KeyError: u'color'
Caught exception in worker thread:
Traceback (most recent call last):
  File "/mnt/hdd1/cao/workspace/data/COCO/panopticapi/utils.py", line 12, in wrapper
    return f(*args, **kwargs)
  File "panopticapi/format_converter.py", line 69, in convert_single_core
    color_gererator = ColorGenerator(categories)
  File "panopticapi/format_converter.py", line 26, in __init__
    self.taken_colors.add(tuple(category['color']))
KeyError: u'color'
Caught exception in worker thread:
Traceback (most recent call last):
  File "/mnt/hdd1/cao/workspace/data/COCO/panopticapi/utils.py", line 12, in wrapper
    return f(*args, **kwargs)
  File "panopticapi/format_converter.py", line 69, in convert_single_core
    color_gererator = ColorGenerator(categories)
  File "panopticapi/format_converter.py", line 26, in __init__
    self.taken_colors.add(tuple(category['color']))
KeyError: u'color'
Caught exception in worker thread:
Traceback (most recent call last):
  File "/mnt/hdd1/cao/workspace/data/COCO/panopticapi/utils.py", line 12, in wrapper
    return f(*args, **kwargs)
  File "panopticapi/format_converter.py", line 69, in convert_single_core
    color_gererator = ColorGenerator(categories)
  File "panopticapi/format_converter.py", line 26, in __init__
    self.taken_colors.add(tuple(category['color']))
KeyError: u'color'
Caught exception in worker thread:
Traceback (most recent call last):
  File "/mnt/hdd1/cao/workspace/data/COCO/panopticapi/utils.py", line 12, in wrapper
    return f(*args, **kwargs)
  File "panopticapi/format_converter.py", line 69, in convert_single_core
    color_gererator = ColorGenerator(categories)
  File "panopticapi/format_converter.py", line 26, in __init__
    self.taken_colors.add(tuple(category['color']))
KeyError: u'color'
Caught exception in worker thread:
Traceback (most recent call last):
  File "/mnt/hdd1/cao/workspace/data/COCO/panopticapi/utils.py", line 12, in wrapper
    return f(*args, **kwargs)
  File "panopticapi/format_converter.py", line 69, in convert_single_core
    color_gererator = ColorGenerator(categories)
  File "panopticapi/format_converter.py", line 26, in __init__
    self.taken_colors.add(tuple(category['color']))
KeyError: u'color'
```

**Comment by alexander-kirillov** [comment]
You should use ‘panoptic_coco_categories.json’ from this repo for ‘--categories_json_file’. The json file has the right ‘color’ field.

**Comment by cao-nv** [comment]
sorry for my mistake, and thanks for you support!

**Comment by eliethesaiyan** [comment]
@alexander-kirillov , the panoptic_annotation(panoptic_train2017) still have no color attribute when using panoptic2detection_coco_format.py , does the detect task needs color in the annotations?

**Comment by Robotatron** [comment]
@alexander-kirillov 
> You should use `panoptic_coco_categories.json` from this repo for `--categories_json_file`. The json file has the right `color` field.

Do we have to modify the `panoptic_coco_categories.json` if we are using a custom dataset with different labels? I am getting an error `Exception: Panoptic coco categories file does not contain                     category with id: 26`
